# Generated by Django 4.1.3 on 2022-11-05 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.car', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicecompany', verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.typemaintenance', verbose_name='Вид ТО'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.car', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='method_recovery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.recoverymethod', verbose_name='Способ восстановления'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='node_failure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.failure', verbose_name='Узел отказа'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicecompany', verbose_name='Сервисная компания'),
        ),
    ]
