# Generated by Django 4.1.3 on 2022-11-06 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_userprofile'),
        ('service', '0003_servicecompany_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecompany',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_service': 'True'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicles.userprofile', verbose_name='Пользователь'),
        ),
    ]
