# Generated by Django 4.1.3 on 2022-11-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_failure_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.servicecompany', verbose_name='Организация, проводившая ТО'),
        ),
    ]
