# Generated by Django 4.1.3 on 2022-11-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_complaints_repair_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='description_failure',
            field=models.TextField(blank=True, null=True, verbose_name='Описание отказа'),
        ),
    ]
