# Generated by Django 4.1.3 on 2022-11-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_controlledbridge_description_and_more'),
        ('service', '0010_alter_complaints_description_failure'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complaints',
            new_name='Complaint',
        ),
    ]
