# Generated by Django 4.1.3 on 2022-11-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_rename_complaints_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='downtime',
        ),
    ]
