# Generated by Django 4.1.3 on 2022-11-06 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_servicecompany_user_alter_failure_description_and_more'),
        ('vehicles', '0003_alter_controlledbridge_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.servicecompany', verbose_name='Сервисная компания'),
        ),
    ]
