# Generated by Django 4.1.3 on 2022-11-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_userprofile_service_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='сonsignee',
            new_name='consignee',
        ),
    ]
