# Generated by Django 4.1.3 on 2022-11-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_controlledbridge_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='equipment',
            field=models.TextField(default='Стандарт', verbose_name='Комплектация (доп. опции)'),
        ),
    ]
